include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # https://dart.dev/tools/linter-rules#style-rules

    # Error rules
    - avoid_print
    - prefer_single_quotes
    - prefer_relative_imports
    - prefer_final_locals
    - unawaited_futures
    - directives_ordering
    - require_trailing_commas

    # Style rules
    - always_declare_return_types
    - annotate_overrides
    - always_put_required_named_parameters_first
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - deprecated_consistency
    - provide_deprecation_message
    - empty_catches
    - file_names
    - flutter_style_todos
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_expression_function_bodies
    - prefer_if_elements_to_conditional_expressions
    - sized_box_shrink_expand
    - sort_child_properties_last
    - sort_constructors_first
    - unnecessary_await_in_return
    - unnecessary_lambdas